### ISSUE TITLE
Sessions and cookies not working!

### ISSUE THREAD

**Issue by nektokomilfo** [Ontraport/PilotPress#41]
Hi! Could you check my http://www.foodwifery.com/login/. Problem is when restart browser users always log out. And after 24 minutes of passive logged out as well... 
But wp admin kepps logged in even after restart browser, session expiring and cookies are set at maximum.

Please help!!

**Comment by aaron-ontraport** [comment]
Hello nektokomlifo,

We are aware that there is an issue with when the browser is closed the reopened, the session is not correctly created again.  We should be releasing a new update that addresses this issue within the next day or so. Also there is an option to keep users logged in longer than normal on the PilotPress settings page at the bottom. Having this turned on helps if users don't take any action for a while or refresh a page as WordPress by default logs them out. 

Hope this helps,

Aaron
