### ISSUE TITLE
The password change email is triggered any time that the wp_update_user() function is called with a user_pass argument

### ISSUE THREAD

**Issue by inphatos** [Ontraport/PilotPress#42]
Hi, we have been receiving complains from our clients that wordpress send unsolicited password reset mails. After some research, wordpress informed us that it had to be a plugin, in this case Pilotpress.

Below, what they told me:
"The password change email is triggered any time that the wp_update_user() function is called with a user_pass argument. If the plugin is not actually changing the password, then it needs to not update the user with a password field in the arguments array.

This is because whether or not you change the password, even to the same password, the database will be changed. WordPress doesn't know the password, only a hash of it. And the same password can be hashed pretty much an infinite number of ways. So if you send it a user_pass, then it actually is rehashing it and updating the entry in the database.

So, please stop calling wp_update_user() with a user_pass field over and over again. Then no more emails will be sent. Instead, consider checking if the user password has actually changed before trying to change it. You can use the wp_check_password() function for that."

I hope to see this solved soon, everyday we receive complains about this situation.

Kind Regards

**Comment by bburleson-op** [comment]
Hi inphatos,

You're right, we were using wp_update_user() with a user_pass argument to make sure the WP user password is synced with the password set in ONTRAPORT. WordPress recently added the email alert functionality to that method.

We have an update ready that will fix this and we will release it today.

Thank you for your attention and thank you for using ONTRAPORT and PilotPress!
Cheers,
Ben
