### ISSUE TITLE
Failed to load ...pilotpress/pilotpress.php?ping=js39

### ISSUE THREAD

**Issue by oakwoodgates** [Ontraport/PilotPress#46]
I am getting this error on Cloudways hosting. They replied that "Ping is blocked by us on server level". This is conflicting with tinymce and WordPress editor. Is there a fix/patch available? 

Thanks!

**Comment by ONTRAPORT-Frank** [comment]
Can you please submit a ticket to our support team at support@ontraport.com? There are a couple of things that can cause a conflict with PilotPress and the WP default editor, so they will want to get some more info from you. Please include your admin username for ONTRAPORT or your account number in your email! Please let me know if you have any questions!
