### ISSUE TITLE
wpdb::escape is deprecated

### ISSUE THREAD

**Issue by kylewebdev** [Ontraport/PilotPress#47]
When I turn on WP_DEBUG, I get this notice all over my site.
`Notice: wpdb::escape is deprecated since version 3.6.0! Use wpdb::prepare() or esc_sql() instead.`

I did a search for `wpdb->escapse` in my `/wp-content` folder and found 5 instances of `$wpdb->escape` being used in `/pilotpress/pilotpress.php`.

**Comment by ONTRAPORT-Frank** [comment]
Thanks, Kyle! I entered a dev ticket for our developers.

**Comment by ONTRAPORT-Frank** [comment]
This is corrected as of version 1.9.8 released on Aug. 29, 2017.

**Comment by ONTRAPORT-Frank** [comment]
This is corrected as of version 1.9.8, released Aug. 29, 2017.
